name: Remote Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: On
  IS_GITHUB_WORKFLOW: On

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - name: Use cached LLVM if available
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/llvm
          key: ${{runner.os}}-llvm-13.0.1-${{ hashFiles('**/*.txt') }}
          restore-keys: |
            ${{runner.os}}-llvm-13.0.1-
      - name: Download LLVM (Unix)
        if: steps.cache-llvm.outputs.cache-hit != 'true' && matrix.os != 'windows-latest'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0.1"
          directory: ${{github.workspace}}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      # For some god-forsaken reason, there is no prebuilt version of LLVM for developing on Windows.
      # Every version comes with llvm-config, LLVMConfig.cmake, and other files needed, expect Windows!
      # Which means we're gonna have to spend an hour or so compiling from scratch (Github willing)
      # At least we have ninja
      # Oh and by the way, we can't even extract it without downloading another program,
      # since the included 'tar' can't extract .tar.xz files.
      # Not only that, but 'tar' will instead fail silently and return 0, as if it was successful!
      # It took me so long to realize this, until I ran `tar --version` just to see that xz is not supported in the provided build.
      - name: Download xz (Windows)
        if: steps.cache-llvm.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        run: |
          curl -o xz-windows.7z https://tukaani.org/xz/xz-5.2.5-windows.7z
          mkdir xz-windows
          cd xz-windows
          7z x xz-windows.7z
          ls
          bin_x86-64/xz --version
      - name: Download LLVM Source Code (Windows)
        if: steps.cache-llvm.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        run: |
          curl -o llvm-source-tree.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/llvm-13.0.1.src.tar.xz
          7z x llvm-source-tree.tar.xz
          ls
      - name: Build LLVM from Source (Windows)
        if: steps.cache-llvm.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        run:
          ls llvm-source-tree
      - name: Install libcurl (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Name required extra libraries (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: echo 'extra_required_libs=-lz -lpsapi -lshell32 -lole32 -luuid -ladvapi32' >> $GITHUB_ENV
      - name: Name required extra libraries (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        run: echo 'extra_required_libs=-lldap -lpthread -lz -lcurses' >> $GITHUB_ENV
      - name: Name required extra libraries (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: echo 'extra_required_libs=-ldl -lpthread -lz -lcurses -lm' >> $GITHUB_ENV
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure
        run: |
          ls ${{github.workspace}}/llvm/lib/cmake
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/llvm -DADEPT_LINK_LLVM_STATIC=On -DEXTRA_REQUIRED_LIBS="${{env.extra_required_libs}}" -B ${{github.workspace}}/build -G Ninja
        env:
          LLVM_DIR: ${{github.workspace}}/llvm/lib/cmake
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Archive Build Result
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: build
          outPath: build-${{ matrix.os }}.tar.gz
      - name: Archive E2E Infrastructure
        uses: a7ul/tar-action@v1.1.0
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          command: c
          cwd: tests
          files: e2e
          outPath: e2e.tar.gz
      - name: Archive Support Libraries Infrastructure
        uses: a7ul/tar-action@v1.1.0
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          command: c
          files: res
          outPath: res.tar.gz
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-archive
          path: build-${{ matrix.os }}.tar.gz
      - name: Upload E2E Testing Infrastructure Artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: e2e-archive
          path: e2e.tar.gz
      - name: Upload Resources Artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: res
          path: res.tar.gz
      - name: Upload LICENSE Artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: LICENSE
          path: LICENSE
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.x' 
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.os }}-archive
      - name: Download E2E Testing Infrastructure Artifact
        uses: actions/download-artifact@v3
        with:
          name: e2e-archive
      - name: Unpack 1/2
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          files: e2e.tar.gz
      - name: Unpack 2/2
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          files: build-${{ matrix.os }}.tar.gz
      - name: Unit Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}
      - name: E2E Test
        working-directory: ${{github.workspace}}/e2e
        run: python3 e2e-runner.py ../build/adept
  build-windows-installer:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest-archive
      - name: Download Support Libraries Artifact
        uses: actions/download-artifact@v3
        with:
          name: res
      - name: Download LICENSE Artifact
        uses: actions/download-artifact@v3
        with:
          name: LICENSE
      - name: Unpack Build Artifact
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          files: build-windows-latest.tar.gz
      - name: Unpack Support Libraries Artifact
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          files: res.tar.gz
      - name: Checkout Adept Standard Library
        uses: actions/checkout@v3
        with:
          repository: 'AdeptLanguage/AdeptImport'
          path: 'AdeptImport'
      - name: Checkout Adept Default Configuration
        uses: actions/checkout@v3
        with:
          repository: 'AdeptLanguage/Config'
          path: 'AdeptConfig'
      - name: Checkout Windows Installer Source Code
        uses: actions/checkout@v3
        with:
          repository: 'IsaacShelton/AdeptWindowsInstaller'
          path: 'AdeptWindowsInstaller'
      - name: Pre-package
        shell: bash
        run: mkdir -p stage
      - name: Generate GUID
        shell: bash
        run: echo -n "::set-output name=guid::" && python3 AdeptWindowsInstaller/generate-guid.py
        id: guid
      - name: Perform substitutions
        shell: bash
        run: >
          sed -i AdeptWindowsInstaller/Adept-X.X-installer.iss -e 's/__STAGING_AREA__/..\/stage/g' -e 's/__OUTPUT_DIRECTORY__/./g' -e 's/__FAVICON_DIRECTORY__/..\/res/g' -e 's/adeptX-X/adept-nightly/g' -e 's/X.X/nightly/g' -e 's/{7D143E16-9268-4F20-A0FA-8B30D8B14ECA}/${{steps.guid.outputs.guid}}/g'
      - name: Stage
        shell: bash
        run: |
          mkdir -p stage
          mv build/adept.exe stage/adept.exe
          mv res/necessities/windows/* stage/
          mv AdeptWindowsInstaller/adeptX-X.bat stage/adept-nightly.bat
          mv AdeptConfig/adept.config stage/adept.config
          mv AdeptImport stage/import
          mv LICENSE stage/LICENSE
      - name: Package as Installer
        run: iscc AdeptWindowsInstaller/Adept-X.X-installer.iss
      - name: Upload Windows Installer Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: AdeptWindowsInstaller/Adept-nightly-installer.exe
  build-macos-installer:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.x' 
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-macos-latest-archive
      - name: Unpack
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          files: build-macos-latest.tar.gz
      - name: Checkout macOS Installer Builder
        uses: actions/checkout@v3
        with:
          repository: 'IsaacShelton/macOS-installer-builder'
          ref: 'v1.0.0'
          path: 'macOS-installer-builder'
      - name: Checkout Adept Standard Library
        uses: actions/checkout@v3
        with:
          repository: 'AdeptLanguage/AdeptImport'
          path: 'AdeptImport'
      - name: Checkout Adept Default Configuration
        uses: actions/checkout@v3
        with:
          repository: 'AdeptLanguage/Config'
          path: 'AdeptConfig'
      - name: Download Adept Cross Compilation Support
        run: wget -O AdeptCrossCompilation.zip https://github.com/IsaacShelton/AdeptCrossCompilation/releases/download/2.4/AdeptCrossCompilation-MacOS-to-Windows.zip
      - name: Unpack Cross Compilation Support
        run: unzip AdeptCrossCompilation.zip
      - name: Stage Application Files
        working-directory: ${{github.workspace}}/macOS-installer-builder
        run: |
          rm -rf stage/application
          mkdir -p stage/application
          mv ../AdeptImport stage/application/import
          mv ../AdeptCrossCompilation-MacOS-to-Windows/cross-compile-windows stage/application/cross-compile-windows
          mv ../AdeptConfig/adept.config stage/application/adept.config
          mv ../build/adept stage/application/adept
      - name: Stage Installer Files
        working-directory: ${{github.workspace}}/macOS-installer-builder
        run: |
          sed -i '' -e s/Adept\ 2.6/Adept\ Nightly/g stage/installer/welcome.html
          sed -i '' -e s/Adept\ 2.6/Adept\ Nightly/g -e s/adept2-6/adept-nightly/g stage/installer/conclusion.html
          sed -i '' -e s/adept2-6/adept-nightly/g -e s/2.6.0/Nightly/g stage/installer/postinstall
      - name: Package as Installer
        working-directory: ${{github.workspace}}/macOS-installer-builder
        run: python3 src/build-installer.py Adept nightly
      - name: Upload Installer Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-installer
          path: macOS-installer-builder/build/Adept-nightly-installer.pkg
  deploy:
    needs: [test, build-windows-installer, build-macos-installer]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact (windows-latest)
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest-archive
      - name: Download Build Artifact (macos-latest)
        uses: actions/download-artifact@v3
        with:
          name: build-macos-latest-archive
      - name: Download Build Artifact (ubuntu-latest)
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu-latest-archive
      - name: Download Windows Installer Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-installer
      - name: Download macOS Installer Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-installer
      - name: Pre-Unpack
        run: mkdir windows-latest macos-latest ubuntu-latest
      - name: Unpack Windows Build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: windows-latest
          files: build-windows-latest.tar.gz
      - name: Unpack macOS Build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: macos-latest
          files: build-macos-latest.tar.gz
      - name: Unpack Ubuntu Build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: ubuntu-latest
          files: build-ubuntu-latest.tar.gz
      - name: Stage
        run: |
          mkdir stage
          mv windows-latest/build/adept.exe stage/x86_64-Windows-adept.exe
          mv macos-latest/build/adept stage/arm64-MacOS-adept
          mv ubuntu-latest/build/adept stage/x86_64-Ubuntu-adept
          mv Adept-nightly-installer.pkg stage/Adept-nightly-installer.pkg
          mv Adept-nightly-installer.exe stage/Adept-nightly-installer.exe
      - name: Release
        uses: IsaacShelton/update-existing-release@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: Nightly
          replace: true
          files: >
            stage/x86_64-Windows-adept.exe
            stage/arm64-MacOS-adept
            stage/x86_64-Ubuntu-adept
            stage/Adept-nightly-installer.pkg
            stage/Adept-nightly-installer.exe
